image: gitpod/workspace-full-vnc

tasks:
- name: SETUP - Download data
  init: |
    cd /workspace
    curl -L "https://gitlab.com/wtsi-grit/rapid-curation/-/archive/main/rapid-curation-main.tar.gz?path=test_data" | tar xzf -
    mv rapid-curation-main-test_data/test_data ./
    rmdir rapid-curation-main-test_data
    gunzip test_data/*.gz
    
- name: SETUP - Download PretextView
  init: |
    cd /workspace
    wget  https://github.com/wtsi-hpag/PretextView/releases/download/0.2.5/PretextView_Linux-x86-64.zip
    unzip PretextView_Linux-x86-64.zip

- name: SETUP - Download the rapid-curation scripts
  init: |
    cd /workspace
    wget  https://gitlab.com/wtsi-grit/rapid-curation/-/raw/main/rapid_split.pl \
          https://gitlab.com/wtsi-grit/rapid-curation/-/raw/main/rapid_join.pl

- name: PRETEXT-TO-AGP
  init: |
    cd /workspace
    git clone https://github.com/sanger-tol/agp-tpf-utils.git

    /workspace/mambaforge/bin/python3 -m pip install agp-tpf-utils/

    echo 'alias pretext-to-agp="/workspace/mambaforge/bin/python3 agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py"'

    
- name: MAMBA ENVIRONMENT
  init: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n rapid -c bioconda perl-bioperl seqtk pyfastaq click ruff -y
    gp sync-done bundle

- name: Main Terminal
  init: gp sync-await bundle # Wait for previous 'inits' to complete
  command: |
    cd /workspace
    chmod a+x *.pl *.py
    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate rapid
    export PATH=/workspace:$PATH
    clear

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod


